# Generated by Django 3.0.7 on 2020-06-15 19:03

import accounting.models.user_models
import accounting.utils
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_org_store_branch_vendor_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('file', models.FileField(upload_to=accounting.utils.upload_image_to)),
                ('is_digitized', models.BooleanField(default=False)),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=accounting.models.user_models.get_super_user_id,
                                                 on_delete=django.db.models.deletion.CASCADE,
                                                 to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('invoice_num', models.CharField(max_length=30, verbose_name='Invoice Number')),
                ('date', models.DateField()),
                ('total_amount', models.FloatField(max_length=99999999.99)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices',
                                             to='accounting.Branch')),
                ('document',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('price', models.FloatField(max_length=99999.99)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField(editable=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(max_length=99999.99)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_rels',
                                              to='accounting.Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_rels',
                                           to='accounting.Item')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices',
                                    to='accounting.Vendor'),
        ),

        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name', 'branch'], name='accounting__name_74314f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'branch')},
        ),
        migrations.AlterUniqueTogether(
            name='invoicelineitem',
            unique_together={('invoice', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_num', 'vendor')},
        ),
    ]
