# Generated by Django 3.0.7 on 2020-06-14 21:16

import accounting.models.user_models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_document_invoice_invoicelineitem_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='branch',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounting.Store'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(default=accounting.models.user_models.get_super_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.Branch'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Document'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_num',
            field=models.CharField(max_length=30, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.Vendor'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_rels', to='accounting.Invoice'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_rels', to='accounting.Item'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(default=accounting.models.user_models.get_super_user_id, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='accounting.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_num', 'vendor')},
        ),
        migrations.AlterUniqueTogether(
            name='invoicelineitem',
            unique_together={('invoice', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'branch')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name', 'branch'], name='accounting__name_74314f_idx'),
        ),
    ]
